name: test
on:
  push:
  pull_request:

jobs:
  release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        # Version as indicated in the metadata, e.g., 3.2.5-rc
        METADATA_VERSION=$(jq -r '.version' app/release_metadata.json)

        # We only need the first part of the version, e.g. 3.2.5, for the milestone recognition. Split on the dash (-) character.
        METADATA_ARRAY=(${METADATA_VERSION//-/ })
        POSSIBLE_MILESTONE=${METADATA_ARRAY[0]}

        # In case the Jar below fails, fall back to a default text
        echo "MAUTIC_CHANGELOG=\"**Based on Mautic's version number (${POSSIBLE_MILESTONE}), we tried finding a milestone with the same name. We couldn't find it though. Make sure it exists (and re-run GitHub Actions) or add a changelog manually!**\"" >> $GITHUB_ENV

        # Download changelog generator
        wget https://github.com/spring-io/github-changelog-generator/releases/download/v0.0.5/github-changelog-generator.jar

        # Copy of release-notes.yml to root folder needed, since the Jar can't read from hidden folders anymore (bug): https://github.com/Decathlon/release-notes-generator-action/pull/21
        cp ./.github/release-notes.yml ./release-notes.yml
        java -jar ./github-changelog-generator.jar --spring.config.location="./release-notes.yml" ${POSSIBLE_MILESTONE} mautic-changelog.txt

        echo 'MAUTIC_CHANGELOG<<EOF' >> $GITHUB_ENV
        cat mautic-changelog.txt >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

        echo ${{ env.MAUTIC_CHANGELOG }}
